package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, TOKEN, FRIEND_REQUEST, FRIEND_ACCEPT, VIEW_FILES, TELL_FILES, ADD_FILE, REMOVE_FILE, HEARTBEAT, IS_ALIVE, RIP_NODE, IS_ALIVE_RESPONSE, SAVE_BACKUP, REMOVE_BACKUP
}
